### ISSUE TITLE
Running lammps on HPC cluster

### ISSUE THREAD

**Issue by warisa-r** [warisa-r/ReaxCeriaEfield#5]
An issue is presented with the installment of shared library on cluster's python. I am currently trying to usethe stable version but this means we need to work with modern reaxff

- [x] Get lammps to work on cluster's python
- [x] Change the npt trial script to be compatible with the current lammps
- [x] Try to successfully do one job on hpc on only 1 task
- [x] Run with 4 task using mpi https://docs.lammps.org/stable/Python_install.html
- [ ] Study how MPI actually works with lammps and is there a way to run nvt or npt with omp threads

**Comment by warisa-r** [comment]
@aramos27 @YiyangZhuu Please keep an eye on this issue before starting the process of installing lammps on your cluster node

**Comment by warisa-r** [comment]
Still make yes-reaxff before make mode=shared mpi

**Comment by warisa-r** [comment]
Could you please try the new reaxff for surface energy @YiyangZhuu. I think I did try energy vacancy with the modern version and Prof deems the difference acceptable.

The lammps 2017 is not compatible with Python in the cluster so we must use lammps2Aug2023 stable version instead.

**Comment by YiyangZhuu** [comment]
copy that, new version is much easier to use:)

________________________________

**Comment by warisa-r** [comment]
@YiyangZhuu @aramos27 I have found the way to run npt and nvt on the cluster now. Let me know when your code is ready. Basically please structure it the way it was written in README.md. 

**Very important is that run.py should be .py not a Jupyter notebook since I'm only familiar with how to run a script that a notebook**

Before uploading the simulation folder, please **make sure it runs on the stable version of lammps for both simulations by using small time steps** since I cannot receive a notification if something goes wrong.

You guys are going to want to run this on the surface 111, correct? I assume like the paper with 500 ps so 500,000 timesteps. That is going to take a long while. My scripts are in `npt_nvt_standard_sim` folder. I haven't checked the correctness but plotted the lattice constant and observed the behavior roughly. 

The appropriate p_damp and T_damp and other parameters I take you guys are going to find an optimal and not just simply take 100 or input yes without any reasons like me.

Tag me or let me know when your scripts are ready. Everything is already functional from this side.

**Comment by warisa-r** [comment]
I also managed to run it successfully with MPI! Hooray! I will merge the functional script tmr.

**Comment by warisa-r** [comment]
@YiyangZhuu @aramos27 The result from running it on the cluster is pushed.
