### ISSUE TITLE
change to stable version

### ISSUE THREAD

**Issue by YiyangZhuu** [warisa-r/ReaxCeriaEfield#7]
track the differences when using stable version of lammps

**Comment by YiyangZhuu** [comment]
surface energy for stable: (old) [paper]
E_surf_110: 1.001 (1.004) [1.08(reaxff) and 1.09(PBE+U)]
E_surf_111: 0.78 (0.78) [0.84(reaxff) and 0.71(PBE+U)]

**Comment by warisa-r** [comment]
For the new version?

**Comment by warisa-r** [comment]
Vacancy energy for 11Aug2017
Dissociation energy of O2: 5.461671531454713 eV (5.45 eV)
Vacancy formation energy: 2.897698082776237 eV (2.95 eV)

**Comment by warisa-r** [comment]
Hereby close since everything is recorded. We may come back to this once we write the report.
